import FeatureNames from '../constants/FeatureNames';

export default [
    {
        feature_name: FeatureNames.HOMEPAGE_HEADER_LOCATION,
        enabled: false,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_HEADER_SEARCH_CATEGORY_SELECTOR,
        enabled: false,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_HEADER_SEARCH_BOX,
        enabled: true,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_HEADER_SHOPPING_CART,
        enabled: false,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_HEADER_USER_PROFILE,
        enabled: false,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_HEADER_NAVLINKS,
        enabled: true,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_HEADER_CALL_TO_ORDER,
        enabled: false,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_ORDER_MEDICINE_SECTION,
        enabled: true,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_ORDER_MEDICINE_SUBSCRIBE_NOW_BUTTON,
        enabled: true,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_ORDER_MEDICINE_UPLOAD_RX_BUTTON,
        enabled: true,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_ORDER_MEDICINE_NORX_BUTTON,
        enabled: true,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_HOW_IT_WORKS_SECTION,
        enabled: true,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_HOW_IT_WORKS_RECIPE,
        enabled: true,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_HOW_IT_WORKS_MEDIA_FILE,
        enabled: true,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_DYNAMIC_PAST_ORDER_LINK_SECTION,
        enabled: false,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_RECENTLY_VIEWED_SECTION,
        enabled: false,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_SHOP_HEALTH_PRODUCTS_SECTION,
        enabled: false,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_SHOP_HEALTH_PRODUCTS_SHOP_BY_CATEGORY_SECTION,
        enabled: false,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_SHOP_HEALTH_PRODUCTS_SHOP_BY_CONCERN_SECTION,
        enabled: false,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_MEDLIFE_ESSENTIALS_SECTION,
        enabled: false,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_TOP_BRANDS_SECTION,
        enabled: false,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_BOOK_LAB_TEST_SECTION,
        enabled: false,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_DOCTOR_CONSULTATION_SECTION,
        enabled: true,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_TESTIMONIAL_SECTION,
        enabled: true,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_PARTNER_WITH_US_SECTION,
        enabled: true,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_HEALTH_ARTICLES_SECTION,
        enabled: true,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_MEDLIFE_CERTIFICATES_SECTION,
        enabled: true,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_CITIES_WE_SERVE_SECTION,
        enabled: true,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_CITIES_WE_SERVE_PINCODE_CHECK_SECTION,
        enabled: true,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_FOOTER_SECTION,
        enabled: true,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_FOOTER_SOCIAL_MEDIA_SECTION,
        enabled: true,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_FOOTER_DOWNLOAD_MOBILE_APP_SECTION,
        enabled: true,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_FOOTER_SUBSCRIBE_SECTION,
        enabled: true,
        source: 'WEB',
        version: '',
    },
    {
        feature_name: FeatureNames.HOMEPAGE_FOOTER_TOP_SEARCHED_SECTION,
        enabled: true,
        source: 'WEB',
        version: '',
    },
];
