import keymirror from 'keymirror';

export default keymirror({
    HOMEPAGE_HEADER_LOCATION: null,
    HOMEPAGE_HEADER_SEARCH_CATEGORY_SELECTOR: null,
    HOMEPAGE_HEADER_SEARCH_BOX: null,
    HOMEPAGE_HEADER_SHOPPING_CART: null,
    HOMEPAGE_HEADER_USER_PROFILE: null,
    HOMEPAGE_HEADER_NAVLINKS: null,
    HOMEPAGE_HEADER_CALL_TO_ORDER: null,

    HOMEPAGE_HEADER_BANNER_SECTION: null,
    HOMEPAGE_HEADER_BANNER_SECTION_DESCRIPTION: null,
    HOMEPAGE_HEADER_BANNER_SECTION_BANNER: null,
    HOMEPAGE_HEADER_USP_SECTION: null,

    HOMEPAGE_ORDER_MEDICINE_SECTION: null,
    HOMEPAGE_ORDER_MEDICINE_SUBSCRIBE_NOW_BUTTON: null,
    HOMEPAGE_ORDER_MEDICINE_UPLOAD_RX_BUTTON: null,
    HOMEPAGE_ORDER_MEDICINE_NORX_BUTTON: null,

    HOMEPAGE_HOW_IT_WORKS_SECTION: null,
    HOMEPAGE_HOW_IT_WORKS_RECIPE: null,
    HOMEPAGE_HOW_IT_WORKS_MEDIA_FILE: null,

    HOMEPAGE_DYNAMIC_PAST_ORDER_LINK_SECTION: null,

    HOMEPAGE_RECENTLY_VIEWED_SECTION: null,

    HOMEPAGE_SHOP_HEALTH_PRODUCTS_SECTION: null,
    HOMEPAGE_SHOP_HEALTH_PRODUCTS_SHOP_BY_CATEGORY_SECTION: null,
    HOMEPAGE_SHOP_HEALTH_PRODUCTS_SHOP_BY_CONCERN_SECTION: null,

    HOMEPAGE_MEDLIFE_ESSENTIALS_SECTION: null,

    HOMEPAGE_TOP_BRANDS_SECTION: null,

    HOMEPAGE_BOOK_LAB_TEST_SECTION: null,

    HOMEPAGE_DOCTOR_CONSULTATION_SECTION: null,

    HOMEPAGE_TESTIMONIAL_SECTION: null,

    HOMEPAGE_PARTNER_WITH_US_SECTION: null,

    HOMEPAGE_HEALTH_ARTICLES_SECTION: null,

    HOMEPAGE_MEDLIFE_CERTIFICATES_SECTION: null,

    HOMEPAGE_CITIES_WE_SERVE_SECTION: null,
    HOMEPAGE_CITIES_WE_SERVE_PINCODE_CHECK_SECTION: null,

    HOMEPAGE_FOOTER_SECTION: null,
    HOMEPAGE_FOOTER_SOCIAL_MEDIA_SECTION: null,
    HOMEPAGE_FOOTER_DOWNLOAD_MOBILE_APP_SECTION: null,
    HOMEPAGE_FOOTER_SUBSCRIBE_SECTION: null,
    HOMEPAGE_FOOTER_TOP_SEARCHED_SECTION: null,
});
